name: Mailer CI

# Define when the workflow should run
on:
  push:
    branches:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Define the operating system

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Access the repository
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -  # Install Poetry
        poetry --version  # Check Poetry version

    - name: Install dependencies
      run: |
        poetry install  # Install the package and dependencies

    - name: Build documentation with Sphinx
      run: |
        poetry run sphinx-apidoc -o docs/source . 
        # Build Sphinx documentation
        poetry run sphinx-build -b html docs/source docs/build  # Generate HTML docs
        
    - name: Run the alert script (optional)
      run: |
        poetry run python alert.py 
    
    - name: Verify Documentation
      run: |
        ls -la docs/build  # Make sure Sphinx built the documentation
